// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbzaiixsalxkoaguqbfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiemFpaXhzYWx4a29hZ3VxYmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjM4MzgsImV4cCI6MjA3MjU5OTgzOH0.vQJzhWO35PKOiTv2dVChta2uPvCf39-kLxG1BQo_TZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});